title: FRC 1511 Docs
description: The greatest subteam on 1511.
baseurl: /
url: https://frc1511.github.io
domain: frc1511.github.io

remote_theme: just-the-docs/just-the-docs
color_scheme: thunder

search_enabled: true

markdown: kramdown
highlighter: rouge
  # input: GFM

footer_content: "Rolling Thunder Programming Subteam - The Greatest Subteam on 1511"

callouts_level: quiet # or loud
callouts_opacity: 0.15
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
