title: 1511 Programming
description: >-
  The greatest subteam on 1511.
baseurl: /
url: https://frc1511.github.io
domain: frc1511.github.io

theme: just-the-docs
# color_scheme: dark

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
