title: FRC 1511 Docs
tagline: FRC Team 1511 Rolling Thunder's Programming Website
description: Programming Website for FIRST Robotics Team 1511 Rolling Thunder
description: A centralized place for all of FRC Team 1511 Rolling Thunder's programming documentation. Includes information about our robots, programming tools, and our techniques and best practices for programming our robots.
baseurl: /
url: https://frc1511.github.io
domain: frc1511.github.io
social:
  name: FRC Team 1511 Rolling Thunder
  links:
    - https://penfieldrobotics.com/
    - https://github.com/frc1511
    - https://twitter.com/1511
    - https://facebook.com/penfieldrobotics
    - https://www.instagram.com/firstteam1511/
    - https://www.youtube.com/user/PenfieldRobotics

remote_theme: just-the-docs/just-the-docs

color_scheme: thunder

search_enabled: true

markdown: kramdown
highlighter: rouge
  # input: GFM

footer_content: "Rolling Thunder Programming Subteam - The Greatest Subteam on 1511"

callouts_level: loud # or quiet
callouts_opacity: 0.15
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  joke:
    title: Joke
    color: orange

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
